### PR TITLE
Improvements to package

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change includes several over-due changes to help stream line deployments of new packages:

* Generate rsync hosts allow at install time
* remove 'kill' after stop -- since this feature has caused more trouble than help since it's introduction
* disable yum-cron

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/package/19)

### CODE REVIEW

**Comment by nkinkade** [comment]
One question about keeping all the existing blocks.

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[slicebase/init/setup_rsync.sh, line 24 at r1](https://reviewable.io:443/reviews/m-lab/package/19#-Kz0fvzTh5nsurSwBkOn:-Kz0fvzTh5nsurSwBkOo:bo0x3je) ([raw file](https://github.com/m-lab/package/blob/53cfa52ff1b93eba7e2de0ed3d36b11f7cff5b57/slicebase/init/setup_rsync.sh#L24)):*
> ```Shell
>     | sed -e 's/ /, /g')
> 
> PREVIOUSLY_EXISTING_BLOCKS="108.170.192.0/18, 108.177.0.0/20, 142.250.0.0/15, 172.217.0.0/16, 172.253.0.0/16, 173.194.0.0/16, 192.178.0.0/15, 199.87.241.32/28, 207.223.160.0/20, 209.85.128.0/17, 216.239.32.0/19, 216.58.192.0/19, 64.233.160.0/19, 66.102.0.0/20, 66.249.64.0/19, 70.32.128.0/19, 70.90.219.48/29, 70.90.219.72/29, 72.14.192.0/18, 74.125.0.0/16, 23.228.128.64/26, 8.34.208.0/20, 8.35.192.0/21, 8.35.200.0/23, 108.59.80.0/20, 108.170.192.0/20, 108.170.208.0/21, 108.170.216.0/22, 108.170.220.0/23, 108.170.222.0/24, 162.216.148.0/22, 162.222.176.0/21, 173.255.112.0/20, 192.158.28.0/22, 199.192.112.0/22, 199.223.232.0/22, 199.223.236.0/23, 23.236.48.0/20, 23.251.128.0/19, 107.167.160.0/19, 107.178.192.0/18, 146.148.2.0/23, 146.148.4.0/22, 146.148.8.0/21, 146.148.16.0/20, 146.148.32.0/19, 146.148.64.0/18, 130.211.4.0/22, 130.211.8.0/21, 130.211.16.0/20, 130.211.32.0/19, 130.211.64.0/18, 130.211.128.0/17, 104.154.0.0/15, 104.196.0.0/14, 208.68.108.0/23, 35.184.0.0/14, 35.188.0.0/16"
> ```

What is the motivation behind keeping these blocks? There were all GCP block anyway, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/package/19#-:-Kz0g9oTvc14MI-YpstQ:b-hcbbpq)*

**Comment by stephen-soltesz** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[slicebase/init/setup_rsync.sh, line 24 at r1](https://reviewable.io:443/reviews/m-lab/package/19#-Kz0fvzTh5nsurSwBkOn:-Kz0gnSmnblKsqfMU_nU:b-131bn0) ([raw file](https://github.com/m-lab/package/blob/53cfa52ff1b93eba7e2de0ed3d36b11f7cff5b57/slicebase/init/setup_rsync.sh#L24)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

What is the motivation behind keeping these blocks? There were all GCP block anyway, right?
</blockquote></details>

I guess the motivation is that we don't know which blocks are for google or some legacy partner IP blocks. IIRC, didn't CIRA collect some data directly?

Mostly this is a "don't fix it if it isn't broken" list.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/package/19)*

**Comment by nkinkade** [comment]
:lgtm: ... let's end the madness.

---

Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[slicebase/init/setup_rsync.sh, line 24 at r1](https://reviewable.io:443/reviews/m-lab/package/19#-Kz0fvzTh5nsurSwBkOn:-Kz0hbx6DPTGlspWLO5g:bb6rskq) ([raw file](https://github.com/m-lab/package/blob/53cfa52ff1b93eba7e2de0ed3d36b11f7cff5b57/slicebase/init/setup_rsync.sh#L24)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I guess the motivation is that we don't know which blocks are for google or some legacy partner IP blocks. IIRC, didn't CIRA collect some data directly?

Mostly this is a "don't fix it if it isn't broken" list.
</blockquote></details>

ACK.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/package/19#-:-Kz0hfoaxVDEMTb6vGCh:bnwjb05)*

**Comment by stephen-soltesz** [comment]
Thank you!

**Pull request merged**
